# Generated by Django 5.2.6 on 2025-09-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CachorroFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_id', models.CharField(help_text='ID da raça.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='nome da raça', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição da raça do cachorro.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Anotações pessoais do usuário.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cachorros_favoritos', to='api_dog.pessoa')),
            ],
        ),
    ]
