# Generated by Django 5.2.6 on 2025-09-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachorrofavorito',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='cachorrofavorito',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='cachorrofavorito',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='cachorrofavorito',
            old_name='breed_id',
            new_name='id_raca',
        ),
        migrations.RenameField(
            model_name='cachorrofavorito',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cachorrofavorito',
            old_name='notes',
            new_name='notas',
        ),
    ]
